// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-1',
    aws_cognito_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_HEdL32tGx',
    aws_user_pools_web_client_id: '48jbd9tc7bqqj0j6fgopgdp8i8',
  };
  
  export default awsmobile;